# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLInferenceServiceStub:
    """MLInferenceService — production gRPC contract between the Go backend
    (server) and the Python ML inference service (ml-service).

    Replaces the legacy REST POST /api/predict and /api/train calls with a
    typed, low-latency, TLS-terminated (aburcloud.com) transport.

    Generate:
    protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    proto/ml_service.proto
    python -m grpc_tools.protoc -I proto --python_out=ml-service \
    --grpc_python_out=ml-service proto/ml_service.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/hormuzwatch.ml.MLInferenceService/Predict',
                request_serializer=ml__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Train = channel.unary_unary(
                '/hormuzwatch.ml.MLInferenceService/Train',
                request_serializer=ml__service__pb2.TrainRequest.SerializeToString,
                response_deserializer=ml__service__pb2.TrainResponse.FromString,
                _registered_method=True)


class MLInferenceServiceServicer:
    """MLInferenceService — production gRPC contract between the Go backend
    (server) and the Python ML inference service (ml-service).

    Replaces the legacy REST POST /api/predict and /api/train calls with a
    typed, low-latency, TLS-terminated (aburcloud.com) transport.

    Generate:
    protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    proto/ml_service.proto
    python -m grpc_tools.protoc -I proto --python_out=ml-service \
    --grpc_python_out=ml-service proto/ml_service.proto
    """

    def Predict(self, request, context):
        """Predict returns the ensemble anomaly score + SHAP contributions for a
        single feature vector. Mirrors GET/POST /api/predict semantics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Train triggers an offline (re)fit for a domain. Mirrors /api/train.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ml__service__pb2.PredictRequest.FromString,
                    response_serializer=ml__service__pb2.PredictResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=ml__service__pb2.TrainRequest.FromString,
                    response_serializer=ml__service__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hormuzwatch.ml.MLInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hormuzwatch.ml.MLInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLInferenceService:
    """MLInferenceService — production gRPC contract between the Go backend
    (server) and the Python ML inference service (ml-service).

    Replaces the legacy REST POST /api/predict and /api/train calls with a
    typed, low-latency, TLS-terminated (aburcloud.com) transport.

    Generate:
    protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    proto/ml_service.proto
    python -m grpc_tools.protoc -I proto --python_out=ml-service \
    --grpc_python_out=ml-service proto/ml_service.proto
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hormuzwatch.ml.MLInferenceService/Predict',
            ml__service__pb2.PredictRequest.SerializeToString,
            ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hormuzwatch.ml.MLInferenceService/Train',
            ml__service__pb2.TrainRequest.SerializeToString,
            ml__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
