apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hormuzwatch-dev

resources:
  - 00-dev-workloads.yaml

commonLabels:
  app.kubernetes.io/part-of: hormuzwatch
  environment: dev
