// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/news": {
    params: {};
  };
  "/admin/sources": {
    params: {};
  };
  "/admin/events": {
    params: {};
  };
  "/admin/threats": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/datasets": {
    params: {};
  };
  "/admin/profile": {
    params: {};
  };
  "/admin/audit": {
    params: {};
  };
  "/admin/tracking": {
    params: {};
  };
  "/admin/watchlist": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/analysis": {
    params: {};
  };
  "/intelligence": {
    params: {};
  };
  "/intelligence/:region": {
    params: {
      "region": string;
    };
  };
  "/learn": {
    params: {};
  };
  "/learn/satellite": {
    params: {};
  };
  "/learn/regional": {
    params: {};
  };
  "/learn/anomaly": {
    params: {};
  };
  "/learn/heatmaps": {
    params: {};
  };
  "/learn/adsb": {
    params: {};
  };
  "/learn/ais": {
    params: {};
  };
  "/learn/architecture": {
    params: {};
  };
  "/learn/detection": {
    params: {};
  };
  "/research": {
    params: {};
  };
  "/deploy": {
    params: {};
  };
  "/status": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/admin" | "/admin/news" | "/admin/sources" | "/admin/events" | "/admin/threats" | "/admin/users" | "/admin/settings" | "/admin/datasets" | "/admin/profile" | "/admin/audit" | "/admin/tracking" | "/admin/watchlist" | "/admin/analytics" | "/admin/analysis" | "/intelligence" | "/intelligence/:region" | "/learn" | "/learn/satellite" | "/learn/regional" | "/learn/anomaly" | "/learn/heatmaps" | "/learn/adsb" | "/learn/ais" | "/learn/architecture" | "/learn/detection" | "/research" | "/deploy" | "/status" | "/about" | "/*";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/news" | "/admin/sources" | "/admin/events" | "/admin/threats" | "/admin/users" | "/admin/settings" | "/admin/datasets" | "/admin/profile" | "/admin/audit" | "/admin/tracking" | "/admin/watchlist" | "/admin/analytics" | "/admin/analysis";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "routes/admin/news.tsx": {
    id: "routes/admin/news";
    page: "/admin/news";
  };
  "routes/admin/sources.tsx": {
    id: "routes/admin/sources";
    page: "/admin/sources";
  };
  "routes/admin/events.tsx": {
    id: "routes/admin/events";
    page: "/admin/events";
  };
  "routes/admin/threats.tsx": {
    id: "routes/admin/threats";
    page: "/admin/threats";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/settings.tsx": {
    id: "routes/admin/settings";
    page: "/admin/settings";
  };
  "routes/admin/datasets.tsx": {
    id: "routes/admin/datasets";
    page: "/admin/datasets";
  };
  "routes/admin/profile.tsx": {
    id: "routes/admin/profile";
    page: "/admin/profile";
  };
  "routes/admin/audit.tsx": {
    id: "routes/admin/audit";
    page: "/admin/audit";
  };
  "routes/admin/tracking.tsx": {
    id: "routes/admin/tracking";
    page: "/admin/tracking";
  };
  "routes/admin/watchlist.tsx": {
    id: "routes/admin/watchlist";
    page: "/admin/watchlist";
  };
  "routes/admin/analytics.tsx": {
    id: "routes/admin/analytics";
    page: "/admin/analytics";
  };
  "routes/admin/analysis.tsx": {
    id: "routes/admin/analysis";
    page: "/admin/analysis";
  };
  "routes/public/layout.tsx": {
    id: "routes/public/layout";
    page: "/" | "/intelligence" | "/intelligence/:region" | "/learn" | "/learn/satellite" | "/learn/regional" | "/learn/anomaly" | "/learn/heatmaps" | "/learn/adsb" | "/learn/ais" | "/learn/architecture" | "/learn/detection" | "/research" | "/deploy" | "/status" | "/about";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/intelligence/index.tsx": {
    id: "routes/public/intelligence/index";
    page: "/intelligence";
  };
  "routes/public/intelligence/region.tsx": {
    id: "routes/public/intelligence/region";
    page: "/intelligence/:region";
  };
  "routes/learn-layout.tsx": {
    id: "routes/learn-layout";
    page: "/learn" | "/learn/satellite" | "/learn/regional" | "/learn/anomaly" | "/learn/heatmaps" | "/learn/adsb" | "/learn/ais" | "/learn/architecture" | "/learn/detection";
  };
  "routes/public/learn/index.tsx": {
    id: "routes/public/learn/index";
    page: "/learn";
  };
  "routes/public/learn/satellite.tsx": {
    id: "routes/public/learn/satellite";
    page: "/learn/satellite";
  };
  "routes/public/learn/regional.tsx": {
    id: "routes/public/learn/regional";
    page: "/learn/regional";
  };
  "routes/public/learn/anomaly.tsx": {
    id: "routes/public/learn/anomaly";
    page: "/learn/anomaly";
  };
  "routes/public/learn/heatmaps.tsx": {
    id: "routes/public/learn/heatmaps";
    page: "/learn/heatmaps";
  };
  "routes/public/learn/adsb.tsx": {
    id: "routes/public/learn/adsb";
    page: "/learn/adsb";
  };
  "routes/public/learn/ais.tsx": {
    id: "routes/public/learn/ais";
    page: "/learn/ais";
  };
  "routes/public/learn/architecture.tsx": {
    id: "routes/public/learn/architecture";
    page: "/learn/architecture";
  };
  "routes/public/learn/detection.tsx": {
    id: "routes/public/learn/detection";
    page: "/learn/detection";
  };
  "routes/public/research.tsx": {
    id: "routes/public/research";
    page: "/research";
  };
  "routes/public/deploy.tsx": {
    id: "routes/public/deploy";
    page: "/deploy";
  };
  "routes/public/status.tsx": {
    id: "routes/public/status";
    page: "/status";
  };
  "routes/public/about.tsx": {
    id: "routes/public/about";
    page: "/about";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/auth/login": typeof import("./src/app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./src/app/routes/auth/register.tsx");
  "routes/admin/layout": typeof import("./src/app/routes/admin/layout.tsx");
  "routes/admin/dashboard": typeof import("./src/app/routes/admin/dashboard.tsx");
  "routes/admin/news": typeof import("./src/app/routes/admin/news.tsx");
  "routes/admin/sources": typeof import("./src/app/routes/admin/sources.tsx");
  "routes/admin/events": typeof import("./src/app/routes/admin/events.tsx");
  "routes/admin/threats": typeof import("./src/app/routes/admin/threats.tsx");
  "routes/admin/users": typeof import("./src/app/routes/admin/users.tsx");
  "routes/admin/settings": typeof import("./src/app/routes/admin/settings.tsx");
  "routes/admin/datasets": typeof import("./src/app/routes/admin/datasets.tsx");
  "routes/admin/profile": typeof import("./src/app/routes/admin/profile.tsx");
  "routes/admin/audit": typeof import("./src/app/routes/admin/audit.tsx");
  "routes/admin/tracking": typeof import("./src/app/routes/admin/tracking.tsx");
  "routes/admin/watchlist": typeof import("./src/app/routes/admin/watchlist.tsx");
  "routes/admin/analytics": typeof import("./src/app/routes/admin/analytics.tsx");
  "routes/admin/analysis": typeof import("./src/app/routes/admin/analysis.tsx");
  "routes/public/layout": typeof import("./src/app/routes/public/layout.tsx");
  "routes/public/home": typeof import("./src/app/routes/public/home.tsx");
  "routes/public/intelligence/index": typeof import("./src/app/routes/public/intelligence/index.tsx");
  "routes/public/intelligence/region": typeof import("./src/app/routes/public/intelligence/region.tsx");
  "routes/learn-layout": typeof import("./src/app/routes/learn-layout.tsx");
  "routes/public/learn/index": typeof import("./src/app/routes/public/learn/index.tsx");
  "routes/public/learn/satellite": typeof import("./src/app/routes/public/learn/satellite.tsx");
  "routes/public/learn/regional": typeof import("./src/app/routes/public/learn/regional.tsx");
  "routes/public/learn/anomaly": typeof import("./src/app/routes/public/learn/anomaly.tsx");
  "routes/public/learn/heatmaps": typeof import("./src/app/routes/public/learn/heatmaps.tsx");
  "routes/public/learn/adsb": typeof import("./src/app/routes/public/learn/adsb.tsx");
  "routes/public/learn/ais": typeof import("./src/app/routes/public/learn/ais.tsx");
  "routes/public/learn/architecture": typeof import("./src/app/routes/public/learn/architecture.tsx");
  "routes/public/learn/detection": typeof import("./src/app/routes/public/learn/detection.tsx");
  "routes/public/research": typeof import("./src/app/routes/public/research.tsx");
  "routes/public/deploy": typeof import("./src/app/routes/public/deploy.tsx");
  "routes/public/status": typeof import("./src/app/routes/public/status.tsx");
  "routes/public/about": typeof import("./src/app/routes/public/about.tsx");
  "routes/$": typeof import("./src/app/routes/$.tsx");
};