// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/ml_service.proto

package mlgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeatureVector — the canonical scoring features sent by the Go backend.
// Field numbers match the JSON keys used by the legacy /api/predict payload
// so the two transports stay interchangeable.
type FeatureVector struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TrackId              string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	CourseDelta          float64                `protobuf:"fixed64,2,opt,name=course_delta,json=courseDelta,proto3" json:"course_delta,omitempty"`
	HeadingDelta         float64                `protobuf:"fixed64,3,opt,name=heading_delta,json=headingDelta,proto3" json:"heading_delta,omitempty"`
	SpeedDelta           float64                `protobuf:"fixed64,4,opt,name=speed_delta,json=speedDelta,proto3" json:"speed_delta,omitempty"`
	AverageSpeed         float64                `protobuf:"fixed64,5,opt,name=average_speed,json=averageSpeed,proto3" json:"average_speed,omitempty"`
	SpeedVariance        float64                `protobuf:"fixed64,6,opt,name=speed_variance,json=speedVariance,proto3" json:"speed_variance,omitempty"`
	AisGapMinutes        float64                `protobuf:"fixed64,7,opt,name=ais_gap_minutes,json=aisGapMinutes,proto3" json:"ais_gap_minutes,omitempty"`
	DistRestrictedZone   float64                `protobuf:"fixed64,8,opt,name=dist_restricted_zone,json=distRestrictedZone,proto3" json:"dist_restricted_zone,omitempty"`
	DistHistoricalSite   float64                `protobuf:"fixed64,9,opt,name=dist_historical_site,json=distHistoricalSite,proto3" json:"dist_historical_site,omitempty"`
	EwmaDeviation        float64                `protobuf:"fixed64,10,opt,name=ewma_deviation,json=ewmaDeviation,proto3" json:"ewma_deviation,omitempty"`
	InRestrictedZone     bool                   `protobuf:"varint,11,opt,name=in_restricted_zone,json=inRestrictedZone,proto3" json:"in_restricted_zone,omitempty"`
	NearHistoricalAttack bool                   `protobuf:"varint,12,opt,name=near_historical_attack,json=nearHistoricalAttack,proto3" json:"near_historical_attack,omitempty"`
	Domain               string                 `protobuf:"bytes,13,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FeatureVector) Reset() {
	*x = FeatureVector{}
	mi := &file_proto_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureVector) ProtoMessage() {}

func (x *FeatureVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureVector.ProtoReflect.Descriptor instead.
func (*FeatureVector) Descriptor() ([]byte, []int) {
	return file_proto_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureVector) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *FeatureVector) GetCourseDelta() float64 {
	if x != nil {
		return x.CourseDelta
	}
	return 0
}

func (x *FeatureVector) GetHeadingDelta() float64 {
	if x != nil {
		return x.HeadingDelta
	}
	return 0
}

func (x *FeatureVector) GetSpeedDelta() float64 {
	if x != nil {
		return x.SpeedDelta
	}
	return 0
}

func (x *FeatureVector) GetAverageSpeed() float64 {
	if x != nil {
		return x.AverageSpeed
	}
	return 0
}

func (x *FeatureVector) GetSpeedVariance() float64 {
	if x != nil {
		return x.SpeedVariance
	}
	return 0
}

func (x *FeatureVector) GetAisGapMinutes() float64 {
	if x != nil {
		return x.AisGapMinutes
	}
	return 0
}

func (x *FeatureVector) GetDistRestrictedZone() float64 {
	if x != nil {
		return x.DistRestrictedZone
	}
	return 0
}

func (x *FeatureVector) GetDistHistoricalSite() float64 {
	if x != nil {
		return x.DistHistoricalSite
	}
	return 0
}

func (x *FeatureVector) GetEwmaDeviation() float64 {
	if x != nil {
		return x.EwmaDeviation
	}
	return 0
}

func (x *FeatureVector) GetInRestrictedZone() bool {
	if x != nil {
		return x.InRestrictedZone
	}
	return false
}

func (x *FeatureVector) GetNearHistoricalAttack() bool {
	if x != nil {
		return x.NearHistoricalAttack
	}
	return false
}

func (x *FeatureVector) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`     // vessel | aviation | heatmap
	Features      *FeatureVector         `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"` // backend-computed deltas + geofence context
	Explain       bool                   `protobuf:"varint,3,opt,name=explain,proto3" json:"explain,omitempty"`  // request SHAP contributions
	TrackId       string                 `protobuf:"bytes,4,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *PredictRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PredictRequest) GetFeatures() *FeatureVector {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *PredictRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type ShapContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Contribution  float64                `protobuf:"fixed64,3,opt,name=contribution,proto3" json:"contribution,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"` // "increases_risk" | "decreases_risk"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShapContribution) Reset() {
	*x = ShapContribution{}
	mi := &file_proto_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShapContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapContribution) ProtoMessage() {}

func (x *ShapContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapContribution.ProtoReflect.Descriptor instead.
func (*ShapContribution) Descriptor() ([]byte, []int) {
	return file_proto_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *ShapContribution) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *ShapContribution) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ShapContribution) GetContribution() float64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *ShapContribution) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type PredictResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Domain            string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	TrackId           string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Probability       float64                `protobuf:"fixed64,3,opt,name=probability,proto3" json:"probability,omitempty"`                       // calibrated 0..1
	AnomalyScore      float64                `protobuf:"fixed64,4,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"` // 0..100 (alias of probability*100)
	IsAnomaly         bool                   `protobuf:"varint,5,opt,name=is_anomaly,json=isAnomaly,proto3" json:"is_anomaly,omitempty"`
	RawIforestScore   float64                `protobuf:"fixed64,6,opt,name=raw_iforest_score,json=rawIforestScore,proto3" json:"raw_iforest_score,omitempty"`
	RawLofScore       float64                `protobuf:"fixed64,7,opt,name=raw_lof_score,json=rawLofScore,proto3" json:"raw_lof_score,omitempty"`
	InferenceTimeMs   float64                `protobuf:"fixed64,8,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	ModelVersion      string                 `protobuf:"bytes,9,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ShapContributions []*ShapContribution    `protobuf:"bytes,10,rep,name=shap_contributions,json=shapContributions,proto3" json:"shap_contributions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *PredictResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PredictResponse) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *PredictResponse) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *PredictResponse) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *PredictResponse) GetIsAnomaly() bool {
	if x != nil {
		return x.IsAnomaly
	}
	return false
}

func (x *PredictResponse) GetRawIforestScore() float64 {
	if x != nil {
		return x.RawIforestScore
	}
	return 0
}

func (x *PredictResponse) GetRawLofScore() float64 {
	if x != nil {
		return x.RawLofScore
	}
	return 0
}

func (x *PredictResponse) GetInferenceTimeMs() float64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

func (x *PredictResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *PredictResponse) GetShapContributions() []*ShapContribution {
	if x != nil {
		return x.ShapContributions
	}
	return nil
}

type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Contamination float64                `protobuf:"fixed64,2,opt,name=contamination,proto3" json:"contamination,omitempty"`
	// feature_rows is a flat repeated list of FeatureVector for offline training.
	FeatureRows   []*FeatureVector `protobuf:"bytes,3,rep,name=feature_rows,json=featureRows,proto3" json:"feature_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_proto_ml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_service_proto_rawDescGZIP(), []int{4}
}

func (x *TrainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TrainRequest) GetContamination() float64 {
	if x != nil {
		return x.Contamination
	}
	return 0
}

func (x *TrainRequest) GetFeatureRows() []*FeatureVector {
	if x != nil {
		return x.FeatureRows
	}
	return nil
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "accepted" | "trained" | "error"
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	NSamples      int32                  `protobuf:"varint,3,opt,name=n_samples,json=nSamples,proto3" json:"n_samples,omitempty"`
	Contamination float64                `protobuf:"fixed64,4,opt,name=contamination,proto3" json:"contamination,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_proto_ml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_service_proto_rawDescGZIP(), []int{5}
}

func (x *TrainResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrainResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *TrainResponse) GetNSamples() int32 {
	if x != nil {
		return x.NSamples
	}
	return 0
}

func (x *TrainResponse) GetContamination() float64 {
	if x != nil {
		return x.Contamination
	}
	return 0
}

func (x *TrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ml_service_proto protoreflect.FileDescriptor

const file_proto_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ml_service.proto\x12\x0ehormuzwatch.ml\"\x8e\x04\n" +
	"\rFeatureVector\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12!\n" +
	"\fcourse_delta\x18\x02 \x01(\x01R\vcourseDelta\x12#\n" +
	"\rheading_delta\x18\x03 \x01(\x01R\fheadingDelta\x12\x1f\n" +
	"\vspeed_delta\x18\x04 \x01(\x01R\n" +
	"speedDelta\x12#\n" +
	"\raverage_speed\x18\x05 \x01(\x01R\faverageSpeed\x12%\n" +
	"\x0espeed_variance\x18\x06 \x01(\x01R\rspeedVariance\x12&\n" +
	"\x0fais_gap_minutes\x18\a \x01(\x01R\raisGapMinutes\x120\n" +
	"\x14dist_restricted_zone\x18\b \x01(\x01R\x12distRestrictedZone\x120\n" +
	"\x14dist_historical_site\x18\t \x01(\x01R\x12distHistoricalSite\x12%\n" +
	"\x0eewma_deviation\x18\n" +
	" \x01(\x01R\rewmaDeviation\x12,\n" +
	"\x12in_restricted_zone\x18\v \x01(\bR\x10inRestrictedZone\x124\n" +
	"\x16near_historical_attack\x18\f \x01(\bR\x14nearHistoricalAttack\x12\x16\n" +
	"\x06domain\x18\r \x01(\tR\x06domain\"\x98\x01\n" +
	"\x0ePredictRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x129\n" +
	"\bfeatures\x18\x02 \x01(\v2\x1d.hormuzwatch.ml.FeatureVectorR\bfeatures\x12\x18\n" +
	"\aexplain\x18\x03 \x01(\bR\aexplain\x12\x19\n" +
	"\btrack_id\x18\x04 \x01(\tR\atrackId\"\x84\x01\n" +
	"\x10ShapContribution\x12\x18\n" +
	"\afeature\x18\x01 \x01(\tR\afeature\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\"\n" +
	"\fcontribution\x18\x03 \x01(\x01R\fcontribution\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\"\x9c\x03\n" +
	"\x0fPredictResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12 \n" +
	"\vprobability\x18\x03 \x01(\x01R\vprobability\x12#\n" +
	"\ranomaly_score\x18\x04 \x01(\x01R\fanomalyScore\x12\x1d\n" +
	"\n" +
	"is_anomaly\x18\x05 \x01(\bR\tisAnomaly\x12*\n" +
	"\x11raw_iforest_score\x18\x06 \x01(\x01R\x0frawIforestScore\x12\"\n" +
	"\rraw_lof_score\x18\a \x01(\x01R\vrawLofScore\x12*\n" +
	"\x11inference_time_ms\x18\b \x01(\x01R\x0finferenceTimeMs\x12#\n" +
	"\rmodel_version\x18\t \x01(\tR\fmodelVersion\x12O\n" +
	"\x12shap_contributions\x18\n" +
	" \x03(\v2 .hormuzwatch.ml.ShapContributionR\x11shapContributions\"\x8e\x01\n" +
	"\fTrainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12$\n" +
	"\rcontamination\x18\x02 \x01(\x01R\rcontamination\x12@\n" +
	"\ffeature_rows\x18\x03 \x03(\v2\x1d.hormuzwatch.ml.FeatureVectorR\vfeatureRows\"\xa9\x01\n" +
	"\rTrainResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12\x1b\n" +
	"\tn_samples\x18\x03 \x01(\x05R\bnSamples\x12$\n" +
	"\rcontamination\x18\x04 \x01(\x01R\rcontamination\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\xa6\x01\n" +
	"\x12MLInferenceService\x12J\n" +
	"\aPredict\x12\x1e.hormuzwatch.ml.PredictRequest\x1a\x1f.hormuzwatch.ml.PredictResponse\x12D\n" +
	"\x05Train\x12\x1c.hormuzwatch.ml.TrainRequest\x1a\x1d.hormuzwatch.ml.TrainResponseB7Z5Geospatial-harmuz-watch/server/internal/mlgrpc;mlgrpcb\x06proto3"

var (
	file_proto_ml_service_proto_rawDescOnce sync.Once
	file_proto_ml_service_proto_rawDescData []byte
)

func file_proto_ml_service_proto_rawDescGZIP() []byte {
	file_proto_ml_service_proto_rawDescOnce.Do(func() {
		file_proto_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ml_service_proto_rawDesc), len(file_proto_ml_service_proto_rawDesc)))
	})
	return file_proto_ml_service_proto_rawDescData
}

var file_proto_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ml_service_proto_goTypes = []any{
	(*FeatureVector)(nil),    // 0: hormuzwatch.ml.FeatureVector
	(*PredictRequest)(nil),   // 1: hormuzwatch.ml.PredictRequest
	(*ShapContribution)(nil), // 2: hormuzwatch.ml.ShapContribution
	(*PredictResponse)(nil),  // 3: hormuzwatch.ml.PredictResponse
	(*TrainRequest)(nil),     // 4: hormuzwatch.ml.TrainRequest
	(*TrainResponse)(nil),    // 5: hormuzwatch.ml.TrainResponse
}
var file_proto_ml_service_proto_depIdxs = []int32{
	0, // 0: hormuzwatch.ml.PredictRequest.features:type_name -> hormuzwatch.ml.FeatureVector
	2, // 1: hormuzwatch.ml.PredictResponse.shap_contributions:type_name -> hormuzwatch.ml.ShapContribution
	0, // 2: hormuzwatch.ml.TrainRequest.feature_rows:type_name -> hormuzwatch.ml.FeatureVector
	1, // 3: hormuzwatch.ml.MLInferenceService.Predict:input_type -> hormuzwatch.ml.PredictRequest
	4, // 4: hormuzwatch.ml.MLInferenceService.Train:input_type -> hormuzwatch.ml.TrainRequest
	3, // 5: hormuzwatch.ml.MLInferenceService.Predict:output_type -> hormuzwatch.ml.PredictResponse
	5, // 6: hormuzwatch.ml.MLInferenceService.Train:output_type -> hormuzwatch.ml.TrainResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ml_service_proto_init() }
func file_proto_ml_service_proto_init() {
	if File_proto_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ml_service_proto_rawDesc), len(file_proto_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ml_service_proto_goTypes,
		DependencyIndexes: file_proto_ml_service_proto_depIdxs,
		MessageInfos:      file_proto_ml_service_proto_msgTypes,
	}.Build()
	File_proto_ml_service_proto = out.File
	file_proto_ml_service_proto_goTypes = nil
	file_proto_ml_service_proto_depIdxs = nil
}
