// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: proto/ml_service.proto

package mlgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLInferenceService_Predict_FullMethodName = "/hormuzwatch.ml.MLInferenceService/Predict"
	MLInferenceService_Train_FullMethodName   = "/hormuzwatch.ml.MLInferenceService/Train"
)

// MLInferenceServiceClient is the client API for MLInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MLInferenceService — production gRPC contract between the Go backend
// (server) and the Python ML inference service (ml-service).
//
// Replaces the legacy REST POST /api/predict and /api/train calls with a
// typed, low-latency, TLS-terminated (aburcloud.com) transport.
//
// Generate:
//
//	protoc --go_out=. --go_opt=paths=source_relative \
//	       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	       proto/ml_service.proto
//	python -m grpc_tools.protoc -I proto --python_out=ml-service \
//	       --grpc_python_out=ml-service proto/ml_service.proto
type MLInferenceServiceClient interface {
	// Predict returns the ensemble anomaly score + SHAP contributions for a
	// single feature vector. Mirrors GET/POST /api/predict semantics.
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Train triggers an offline (re)fit for a domain. Mirrors /api/train.
	Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error)
}

type mLInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLInferenceServiceClient(cc grpc.ClientConnInterface) MLInferenceServiceClient {
	return &mLInferenceServiceClient{cc}
}

func (c *mLInferenceServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, MLInferenceService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLInferenceServiceClient) Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, MLInferenceService_Train_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLInferenceServiceServer is the server API for MLInferenceService service.
// All implementations must embed UnimplementedMLInferenceServiceServer
// for forward compatibility.
//
// MLInferenceService — production gRPC contract between the Go backend
// (server) and the Python ML inference service (ml-service).
//
// Replaces the legacy REST POST /api/predict and /api/train calls with a
// typed, low-latency, TLS-terminated (aburcloud.com) transport.
//
// Generate:
//
//	protoc --go_out=. --go_opt=paths=source_relative \
//	       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	       proto/ml_service.proto
//	python -m grpc_tools.protoc -I proto --python_out=ml-service \
//	       --grpc_python_out=ml-service proto/ml_service.proto
type MLInferenceServiceServer interface {
	// Predict returns the ensemble anomaly score + SHAP contributions for a
	// single feature vector. Mirrors GET/POST /api/predict semantics.
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// Train triggers an offline (re)fit for a domain. Mirrors /api/train.
	Train(context.Context, *TrainRequest) (*TrainResponse, error)
	mustEmbedUnimplementedMLInferenceServiceServer()
}

// UnimplementedMLInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLInferenceServiceServer struct{}

func (UnimplementedMLInferenceServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedMLInferenceServiceServer) Train(context.Context, *TrainRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedMLInferenceServiceServer) mustEmbedUnimplementedMLInferenceServiceServer() {}
func (UnimplementedMLInferenceServiceServer) testEmbeddedByValue()                            {}

// UnsafeMLInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLInferenceServiceServer will
// result in compilation errors.
type UnsafeMLInferenceServiceServer interface {
	mustEmbedUnimplementedMLInferenceServiceServer()
}

func RegisterMLInferenceServiceServer(s grpc.ServiceRegistrar, srv MLInferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedMLInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLInferenceService_ServiceDesc, srv)
}

func _MLInferenceService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInferenceService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServiceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLInferenceService_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServiceServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInferenceService_Train_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServiceServer).Train(ctx, req.(*TrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLInferenceService_ServiceDesc is the grpc.ServiceDesc for MLInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hormuzwatch.ml.MLInferenceService",
	HandlerType: (*MLInferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _MLInferenceService_Predict_Handler,
		},
		{
			MethodName: "Train",
			Handler:    _MLInferenceService_Train_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ml_service.proto",
}
