name: terraform-plan

on:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: terraform fmt -check -recursive
      - run: terraform init
        working-directory: terraform
      - run: terraform validate
        working-directory: terraform
      - run: terraform plan -var="alert_email=${{ secrets.ALERT_EMAIL }}"
        working-directory: terraform
