/**
 * HormuzWatch Tactical Icon System — TypeScript Registry
 * =======================================================
 * Central type-safe registry mapping every icon name to its category,
 * intended map behavior, zoom constraints, rotatability, and SVG renderer.
 */

import * as Aircraft from './aircraft';
import * as Infrastructure from './infrastructure';
import * as Maritime from './maritime';

export type IconCategory =
  | 'aircraft'
  | 'maritime'
  | 'infrastructure'
  | 'overlay'
  | 'motion'
  | 'cluster';

export type IconBehavior =
  | 'rotating-symbol' // Live moving contact centered on coord, rotates with heading
  | 'pin'             // Static teardrop pin fixed upright at coordinate
  | 'overlay'         // Status frame overlaying a contact symbol
  | 'animated'        // Vector indicator line/pattern
  | 'cluster';        // Aggregated marker

export interface IconMeta {
  id: string;
  name: string;
  category: IconCategory;
  behavior: IconBehavior;
  rotatable: boolean;
  minZoom?: number;
  maxZoom?: number;
  render: (opts?: any) => string;
}

export const TACTICAL_ICON_REGISTRY: Record<string, IconMeta> = {
  // ── Aircraft ─────────────────────────────────────────────────────────────
  'aircraft-commercial': {
    id: 'aircraft-commercial',
    name: 'Commercial Airliner',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftCommercial,
  },
  'aircraft-cargo': {
    id: 'aircraft-cargo',
    name: 'Cargo Aircraft',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftCargo,
  },
  'aircraft-business': {
    id: 'aircraft-business',
    name: 'Business Jet',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftBusinessJet,
  },
  'aircraft-helicopter': {
    id: 'aircraft-helicopter',
    name: 'Helicopter',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftHelicopter,
  },
  'aircraft-fighter': {
    id: 'aircraft-fighter',
    name: 'Fighter Jet',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftFighter,
  },
  'aircraft-interceptor': {
    id: 'aircraft-interceptor',
    name: 'Interceptor',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftInterceptor,
  },
  'aircraft-bomber': {
    id: 'aircraft-bomber',
    name: 'Strategic Bomber',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftBomber,
  },
  'aircraft-trainer': {
    id: 'aircraft-trainer',
    name: 'Trainer Aircraft',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftTrainer,
  },
  'aircraft-transport': {
    id: 'aircraft-transport',
    name: 'Military Transport',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftTransport,
  },
  'aircraft-awacs': {
    id: 'aircraft-awacs',
    name: 'AWACS Radar Aircraft',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftAwacs,
  },
  'aircraft-tanker': {
    id: 'aircraft-tanker',
    name: 'Aerial Refuel Tanker',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftTanker,
  },
  'aircraft-recon': {
    id: 'aircraft-recon',
    name: 'Reconnaissance Aircraft',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftRecon,
  },
  'aircraft-maritime-patrol': {
    id: 'aircraft-maritime-patrol',
    name: 'Maritime Patrol Aircraft',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftMaritimePatrol,
  },
  'aircraft-uav': {
    id: 'aircraft-uav',
    name: 'UAV / MALE Drone',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftUav,
  },
  'aircraft-large-drone': {
    id: 'aircraft-large-drone',
    name: 'HALE Stealth Drone',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftLargeDrone,
  },
  'aircraft-small-drone': {
    id: 'aircraft-small-drone',
    name: 'Small Quadcopter Drone',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftSmallDrone,
  },
  'aircraft-unknown': {
    id: 'aircraft-unknown',
    name: 'Unknown Aircraft Contact',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftUnknown,
  },
  'aircraft-balloon': {
    id: 'aircraft-balloon',
    name: 'Surveillance Balloon',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: false,
    render: Aircraft.iconAircraftBalloon,
  },
  'aircraft-glider': {
    id: 'aircraft-glider',
    name: 'Glider',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftGlider,
  },
  'aircraft-emergency': {
    id: 'aircraft-emergency',
    name: 'Emergency Flight Signal',
    category: 'aircraft',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Aircraft.iconAircraftEmergency,
  },

  // ── Maritime Vessels ──────────────────────────────────────────────────────
  'vessel-cargo': {
    id: 'vessel-cargo',
    name: 'Cargo Vessel',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselCargo,
  },
  'vessel-container': {
    id: 'vessel-container',
    name: 'Container Ship',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselContainer,
  },
  'vessel-oil-tanker': {
    id: 'vessel-oil-tanker',
    name: 'Crude Oil Tanker',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselOilTanker,
  },
  'vessel-chemical-tanker': {
    id: 'vessel-chemical-tanker',
    name: 'Chemical Tanker',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselChemicalTanker,
  },
  'vessel-lng-carrier': {
    id: 'vessel-lng-carrier',
    name: 'LNG Gas Carrier',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselLngCarrier,
  },
  'vessel-bulk-carrier': {
    id: 'vessel-bulk-carrier',
    name: 'Bulk Carrier',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselBulkCarrier,
  },
  'vessel-passenger': {
    id: 'vessel-passenger',
    name: 'Passenger Vessel',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselPassenger,
  },
  'vessel-cruise': {
    id: 'vessel-cruise',
    name: 'Cruise Ship',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselCruise,
  },
  'vessel-roro': {
    id: 'vessel-roro',
    name: 'RoRo Vehicle Carrier',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselRoro,
  },
  'vessel-fishing': {
    id: 'vessel-fishing',
    name: 'Fishing Boat',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselFishing,
  },
  'vessel-tug': {
    id: 'vessel-tug',
    name: 'Tugboat',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselTug,
  },
  'vessel-pilot': {
    id: 'vessel-pilot',
    name: 'Pilot Boat',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselPilot,
  },
  'vessel-patrol': {
    id: 'vessel-patrol',
    name: 'Patrol Craft',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselPatrol,
  },
  'vessel-fast-attack': {
    id: 'vessel-fast-attack',
    name: 'Fast Attack Craft',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselFastAttack,
  },
  'vessel-coast-guard': {
    id: 'vessel-coast-guard',
    name: 'Coast Guard Cutter',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselCoastGuard,
  },
  'vessel-frigate': {
    id: 'vessel-frigate',
    name: 'Naval Frigate',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselFrigate,
  },
  'vessel-destroyer': {
    id: 'vessel-destroyer',
    name: 'Guided Missile Destroyer',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselDestroyer,
  },
  'vessel-corvette': {
    id: 'vessel-corvette',
    name: 'Corvette',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselCorvette,
  },
  'vessel-carrier': {
    id: 'vessel-carrier',
    name: 'Aircraft Carrier',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselCarrier,
  },
  'vessel-amphibious': {
    id: 'vessel-amphibious',
    name: 'Amphibious Assault Ship',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselAmphibious,
  },
  'vessel-mine-hunter': {
    id: 'vessel-mine-hunter',
    name: 'Minehunter',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselMineHunter,
  },
  'vessel-submarine': {
    id: 'vessel-submarine',
    name: 'Submarine Contact',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselSubmarine,
  },
  'vessel-support': {
    id: 'vessel-support',
    name: 'Naval Auxiliary / Support',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselSupport,
  },
  'vessel-research': {
    id: 'vessel-research',
    name: 'Research Vessel',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselResearch,
  },
  'vessel-dredger': {
    id: 'vessel-dredger',
    name: 'Dredger',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselDredger,
  },
  'vessel-yacht': {
    id: 'vessel-yacht',
    name: 'Motor Yacht',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselYacht,
  },
  'vessel-high-speed': {
    id: 'vessel-high-speed',
    name: 'High Speed Craft (Catamaran)',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselHighSpeedCraft,
  },
  'vessel-unknown': {
    id: 'vessel-unknown',
    name: 'Unknown Vessel Contact',
    category: 'maritime',
    behavior: 'rotating-symbol',
    rotatable: true,
    render: Maritime.iconVesselUnknown,
  },

  // ── Static Infrastructure Pins ──────────────────────────────────────────
  'pin-commercial-airport': {
    id: 'pin-commercial-airport',
    name: 'Commercial Airport',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 5,
    render: Infrastructure.pinCommercialAirport,
  },
  'pin-military-airbase': {
    id: 'pin-military-airbase',
    name: 'Military Airbase',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 4,
    render: Infrastructure.pinMilitaryAirbase,
  },
  'pin-fob': {
    id: 'pin-fob',
    name: 'Forward Operating Base',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinForwardOperatingBase,
  },
  'pin-heliport': {
    id: 'pin-heliport',
    name: 'Heliport',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 8,
    render: Infrastructure.pinHeliport,
  },
  'pin-commercial-port': {
    id: 'pin-commercial-port',
    name: 'Commercial Seaport',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 5,
    render: Infrastructure.pinCommercialPort,
  },
  'pin-container-port': {
    id: 'pin-container-port',
    name: 'Container Terminal',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinContainerPort,
  },
  'pin-oil-terminal': {
    id: 'pin-oil-terminal',
    name: 'Oil Tanker Terminal',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 5,
    render: Infrastructure.pinOilTerminal,
  },
  'pin-lng-terminal': {
    id: 'pin-lng-terminal',
    name: 'LNG Terminal',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 5,
    render: Infrastructure.pinLngTerminal,
  },
  'pin-refinery': {
    id: 'pin-refinery',
    name: 'Oil Refinery',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinRefinery,
  },
  'pin-naval-base': {
    id: 'pin-naval-base',
    name: 'Naval Base',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 4,
    render: Infrastructure.pinNavalBase,
  },
  'pin-coast-guard-base': {
    id: 'pin-coast-guard-base',
    name: 'Coast Guard Station',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinCoastGuardBase,
  },
  'pin-radar-site': {
    id: 'pin-radar-site',
    name: 'Coastal / Air Radar Station',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinRadarSite,
  },
  'pin-air-defense-site': {
    id: 'pin-air-defense-site',
    name: 'Air Defense Battery',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinAirDefenseSite,
  },
  'pin-missile-site': {
    id: 'pin-missile-site',
    name: 'Missile Site',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 6,
    render: Infrastructure.pinMissileSite,
  },
  'pin-comms-tower': {
    id: 'pin-comms-tower',
    name: 'Communications Tower',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 8,
    render: Infrastructure.pinCommunicationsTower,
  },
  'pin-sat-ground-station': {
    id: 'pin-sat-ground-station',
    name: 'Satellite Ground Station',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 7,
    render: Infrastructure.pinSatelliteStation,
  },
  'pin-power-plant': {
    id: 'pin-power-plant',
    name: 'Power Generation Plant',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 7,
    render: Infrastructure.pinPowerPlant,
  },
  'pin-pipeline-station': {
    id: 'pin-pipeline-station',
    name: 'Pipeline Pumping Station',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 7,
    render: Infrastructure.pinPipelineStation,
  },
  'pin-chokepoint': {
    id: 'pin-chokepoint',
    name: 'Maritime Strategic Chokepoint',
    category: 'infrastructure',
    behavior: 'pin',
    rotatable: false,
    minZoom: 3,
    render: Infrastructure.pinChokepoint,
  },
};
