apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hormuzwatch-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yahyaoncloud/HormuzWatch.git
    targetRevision: production-ready
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hormuzwatch-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
