apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - root-app-of-apps.yaml
  - application-prod.yaml
  - application-dev.yaml

commonLabels:
  app.kubernetes.io/part-of: hormuzwatch-gitops
