[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
compose_file=docker-compose.dev.yml
registry_host=127.0.0.1:5000

[local]
localhost ansible_connection=local ansible_user=tp24 target_project_dir=/home/tp24/SHARED/Projects/HormuzWatch

[workstations]
tunkstun ansible_host=192.168.1.51 ansible_user=yahya target_project_dir=/home/yahya/SHARED/Projects/HormuzWatch

[fresh_nodes]
# Template for new blank host
target_node ansible_host=127.0.0.1 ansible_user=ubuntu target_project_dir=/opt/hormuzwatch
