[azure_vm]
# Replace this with the actual output of `terraform output -raw vm_public_ip`
# e.g., 20.20.20.20
<YOUR_VM_PUBLIC_IP>

[azure_vm:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
